addr: ":9090"

storage:
  fs:
    disabled: true

  s3:
    disabled: false
    region: "us-east-1"
    endpoint: "http://localhost:9000"

  azure:
    disabled: true
    account: ""
    connection_string: ""
    account_key: ""
    use_default_credential: false